[package]
name = "pengui"
version = "0.1.0"
authors = ["Clematrics", "Emile Trotignon", "Alatreon42"]
edition = "2018"

[dependencies]
glium = "0.28.0"
nalgebra = "0.23.1"

[build-dependencies]
rustc_version = "0.3.0"

[dev-dependencies]
nalgebra = "0.23.1"
image = "0.23.12"
