name: Rust

on:
  push:
    branches: **
  pull_request:
    branches: **

env:
  CARGO_TERM_COLOR: always

jobs:
  setup:
    runs-on: [ macos-latest ]

    steps:
    - name: Install rust formatter
      run: rustup component add rustfmt --toolchain stable-x86_64-apple-darwin

  build:
    needs: setup
    runs-on: [ ubuntu-latest, macos-latest, windows-latest ]

    steps:
    - uses: actions/checkout@v2
    - name: Format
      run: cargo fmt -- --check
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

